'use strict';

export const SET_SURPLUS_FOOD_LIST = 'SET_SURPLUS_FOOD_LIST';
export const SET_NUMBER_VALIDITY = 'SET_NUMBER_VALIDITY';
export const SET_REQUEST_ACCEPT_STATUS = 'SET_REQUEST_ACCEPT_STATUS';
export const SET_INTIMATION_STATUS = 'SET_INTIMATION_STATUS';
export const SET_PREVIOUS_INTIMATIONS = 'SET_PREVIOUS_INTIMATIONS';
export const SET_PREVIOUS_REQUESTS = 'SET_PREVIOUS_REQUESTS';
