'use strict';

export const SET_SURPLUS_FOOD_LIST = 'SET_SURPLUS_FOOD_LIST';
export const SET_NUMBER_VALIDITY = 'SET_NUMBER_VALIDITY';
export const SET_REQUEST_ACCEPT_STATUS = 'SET_REQUEST_ACCEPT_STATUS';
